from __future__ import annotations
import argparse,hashlib,importlib.util,json,os,shutil,subprocess,sys,tempfile,zipfile
from pathlib import Path
MAIN='0abaed85873c3f8de04765847eb7700b0e20433f';FREEZE='22B0ADBCCF442B0B3654F964E35AB77A044AF7623891E2A60C72B06A94ECE9A3';V185_SHA='AA64B7E093DDE4A707F283774911F2FCAFDB85B1292B41D1F9D8A2B6ECB0C6F8';DIAG_PKG_SHA='5793DB9BB2665CF8BDD6040D7577F6B54F89679CCA5DBA4CC0C6F26658BB9160';DIAG_RESULT_SHA='5A6F3007A2EEDF314DCC78FF8ED511F2AA6CA3861C52C920D70D58227A2714D6';SOURCE_POLICY_SHA='4DFCB76A1C0B524E108334E86915AABCE648E24134FD49169E6728051C564D80';EFFECTIVE_POLICY_SHA='45C66A55D5A04162B6373B7FAA7F025CC523945E64E98C1301240E93D91F7F6A';PROFILE_AMENDMENT_SHA='842E37B757F42D98274E4D7EE3D5495980EADAD5C9D34CAF6B2041E7A8264E35';PROFILE_RECEIPT_SHA='5A02C0A7035CC5AC0E1638CB04E42A238A5C61A97E1AE3A9C0CDEA4E6B231AC9';DECISION_SHA='931607AA75AC8FE16D7792ACFE86BE37AA0BA1E17D269170C677D0F8B132551D';ENGINE_SHA='C31FFD3CBDFF5023923B6A5C5C256F031E9DC372EB5546162125238A3D590386';SC_RECEIPT='FD1228D88F7F7B7498F70F9DB7595A042E94D8293F19D156C5A970C06B775BF5';DATASET_REL=Path('datasets')/'memory_stage_g2'/'alice.stage-g2.g2a.gold-semantic-decomposition.v1';PROFILE_INSTALL='alice-mc10d-glm-public-judge-runtime-profile-amendment-v1';SC_INSTALL='alice-mc10d-public-judge-decision-scoring-amendment-v1'
class Stop(RuntimeError):pass

def req(c,m):
 if not c:raise Stop(m)
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest().upper()
def rj(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def wj(p,o):Path(p).write_text(json.dumps(o,sort_keys=True,separators=(',',':'),ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def safe_extract(zp,out):
 out=Path(out);req(not out.exists(),'extract exists');out.mkdir(parents=True)
 with zipfile.ZipFile(zp) as z:req(z.testzip() is None,'zip crc');z.extractall(out)
def one(d):
 x=[p for p in Path(d).iterdir() if p.is_dir()];req(len(x)==1,'one root');return x[0]
def load(p,n):
 s=importlib.util.spec_from_file_location(n,p);req(s and s.loader,'load');m=importlib.util.module_from_spec(s);sys.modules[n]=m;s.loader.exec_module(m);return m

def validate_diag(vault):
 p=Path(vault)/DATASET_REL/'audits'/'alice-mc10d-repair-qualify-refreeze-v1-3.work'/'judge_qualification'/'diagnostic_glm_q04_v100'/'mc10d_glm_q04_diagnostic_result.json';req(p.is_file() and sha(p)==DIAG_RESULT_SHA,'GLM Q04 diagnostic result missing/hash drift');d=rj(p);req(d.get('diagnostic_only') is True and d.get('qualification_authority') is False and d.get('classification')=='CONFIRMED_THINKING_BUDGET_EXHAUSTION_PERSISTS_THROUGH_12288','diagnostic classification/authority');req(d.get('first_sufficient_non_authoritative_capacity') is None,'diagnostic sufficient capacity drift');req(d.get('family')=='glm' and d.get('task_id')=='Q04_FAKE_SOURCE_HISTORY' and d.get('decision_worker_sha256')==DECISION_SHA,'diagnostic identity');req(d.get('private_data_used') is False and d.get('hidden_MC8_used') is False and d.get('thinking_text_persisted') is False,'diagnostic firewall');a=d.get('attempts') or [];req(len(a)==3,'diagnostic attempt count');exp=[('EXACT_V185_FINAL_ATTEMPT',8192,6144),('CONDITIONAL_CAPACITY_PROBE_8192',12288,8192),('CONDITIONAL_CAPACITY_PROBE_12288',16384,12288)];
 for x,(kind,ctx,budget) in zip(a,exp):req(x.get('kind')==kind and x.get('think') is True and x.get('num_ctx')==ctx and x.get('num_predict')==budget and x.get('content_len')==0 and int(x.get('thinking_len') or 0)>0 and x.get('done_reason')=='length' and x.get('eval_count')==budget,'diagnostic length-exhaustion evidence '+kind)
 print('glm_q04_diagnostic_bound=true classification='+d['classification']+' attempts=6144,8192,12288');return p

def ratify_profile(pkg,vault,diag):
 src=rj(pkg/'authority'/'mc10d_public_judge_qualification_policy_v1_source.json');eff=rj(pkg/'authority'/'mc10d_public_judge_qualification_policy_v1_glm_thinking_off.json');req(sha(pkg/'authority'/'mc10d_public_judge_qualification_policy_v1_source.json')==SOURCE_POLICY_SHA,'source policy hash');req(sha(pkg/'authority'/'mc10d_public_judge_qualification_policy_v1_glm_thinking_off.json')==EFFECTIVE_POLICY_SHA,'effective policy hash');req(src['public_qualification_targets']['glm']['qualified_profile']=={'id':'thinking_on','think':True},'source GLM profile');req(eff['public_qualification_targets']['glm']['qualified_profile']=={'id':'thinking_off','think':False},'effective GLM profile');req(src['public_qualification_targets']['gemma']==eff['public_qualification_targets']['gemma'],'Gemma policy changed');s2=json.loads(json.dumps(src));s2['public_qualification_targets']['glm']['qualified_profile']={'id':'thinking_off','think':False};req(s2==eff,'policy changed beyond GLM qualified_profile');req(sha(pkg/'authority'/'MC10D_GLM_PUBLIC_JUDGE_RUNTIME_PROFILE_AMENDMENT_V1.json')==PROFILE_AMENDMENT_SHA,'profile amendment hash')
 install=Path(vault)/DATASET_REL/'audits'/PROFILE_INSTALL;stage=install.with_name(PROFILE_INSTALL+'.staging');shutil.rmtree(stage,ignore_errors=True);stage.mkdir(parents=True);shutil.copy2(pkg/'authority'/'MC10D_GLM_PUBLIC_JUDGE_RUNTIME_PROFILE_AMENDMENT_V1.json',stage/'MC10D_GLM_PUBLIC_JUDGE_RUNTIME_PROFILE_AMENDMENT_V1.json');shutil.copy2(pkg/'authority'/'mc10d_public_judge_qualification_policy_v1_source.json',stage/'mc10d_public_judge_qualification_policy_v1_source.json');shutil.copy2(pkg/'authority'/'mc10d_public_judge_qualification_policy_v1_glm_thinking_off.json',stage/'mc10d_public_judge_qualification_policy_v1_glm_thinking_off.json');shutil.copy2(diag,stage/'mc10d_glm_q04_diagnostic_result.json')
 receipt={'artifact_id': 'alice.MC10D.glm-public-judge-runtime-profile-ratification-receipt.v1', 'owner_ratified': True, 'ratification_mechanism': 'owner_execution_of_v1.8.6_launcher_before_GLM_qualification', 'canonical_main': '0abaed85873c3f8de04765847eb7700b0e20433f', 'freeze_sha256': '22B0ADBCCF442B0B3654F964E35AB77A044AF7623891E2A60C72B06A94ECE9A3', 'source_policy_sha256': '4DFCB76A1C0B524E108334E86915AABCE648E24134FD49169E6728051C564D80', 'amended_policy_sha256': '45C66A55D5A04162B6373B7FAA7F025CC523945E64E98C1301240E93D91F7F6A', 'diagnostic_result_sha256': '5A6F3007A2EEDF314DCC78FF8ED511F2AA6CA3861C52C920D70D58227A2714D6', 'diagnostic_classification': 'CONFIRMED_THINKING_BUDGET_EXHAUSTION_PERSISTS_THROUGH_12288', 'family': 'glm', 'tag': 'glm-4.7-flash:q4_K_M', 'digest': '4475827791a269b02c8ec49b1c3bc1abb5846bacf3fae015b75d33986322d8f6', 'original_profile': {'id': 'thinking_on', 'think': True}, 'amended_profile': {'id': 'thinking_off', 'think': False}, 'scope': 'GLM_MC10D_PUBLIC_QUALIFICATION_AND_ALL_DOWNSTREAM_USES_OF_THIS_BOUND_GLM_JUDGE', 'num_predict_ladder': [2048, 4096, 6144], 'qualification_passed_by_ratification': False, 'pointwise_start_allowed_by_ratification': False, 'A_SYN_acceptance': False, 'A_SYN_promotion': False, 'model_training': False, 'stage_g_closed': False, 'phase2_replaced': False, 'next_action': 'FRESH_FULL_16_TASK_GLM_QUALIFICATION_THINK_FALSE'};wj(stage/'RATIFICATION_RECEIPT.json',receipt);req(isinstance(rj(stage/'RATIFICATION_RECEIPT.json'),dict),'profile receipt object');req(sha(stage/'RATIFICATION_RECEIPT.json')==PROFILE_RECEIPT_SHA,'profile receipt hash')
 if install.exists():req(sha(install/'RATIFICATION_RECEIPT.json')==PROFILE_RECEIPT_SHA and sha(install/'mc10d_public_judge_qualification_policy_v1_glm_thinking_off.json')==EFFECTIVE_POLICY_SHA,'existing profile amendment differs');shutil.rmtree(stage)
 else:stage.replace(install)
 print('glm_public_judge_runtime_profile_amendment_ratified=true receipt_sha256='+PROFILE_RECEIPT_SHA);print('glm_profile=thinking_off model_and_digest_unchanged=true');print('qualification_passed=false pointwise=false A_SYN_acceptance=false A_SYN_promotion=false training=false');return install

def validate_bundle(out,td):
 d=Path(td)/'ready';safe_extract(out,d);root=one(d);bind=rj(root/'judges'/'mc10d_judge_binding_receipt_v2.json');m={x['family']:x for x in bind['bound_judges']};req(m['gemma']['profile']=={'id':'thinking_on','think':True},'Gemma binding profile');req(m['glm']['profile']=={'id':'thinking_off','think':False},'GLM binding profile');req(m['glm'].get('profile_amendment_receipt_sha256')==PROFILE_RECEIPT_SHA,'GLM binding amendment receipt');rec=rj(root/'POINTWISE_READY_RECEIPT.json');req(rec.get('effective_A_SYN_candidate_pool')==287 and rec.get('deferred_slots')==1 and rec.get('MC10D_pointwise_scope_judge_screen_start_allowed') is True and rec.get('MC10D_full_simulation_falsification_start_allowed') is False,'pointwise-ready boundary');return bind

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--repo-root',default=r'C:\A.L.I.C.E-main');ap.add_argument('--vault-root',default=r'C:\ALICE_Vault');ap.add_argument('--freeze-bundle',default=str(Path.home()/'Downloads'/'ALICE_MC10D_PREEXECUTION_FREEZE_BUNDLE_v1.1.zip'));ap.add_argument('--output',default=str(Path.home()/'Downloads'/'ALICE_MC10D_POINTWISE_READY_BUNDLE_v1.8.6.zip'));ap.add_argument('--timeout-hours',type=int,default=12);ap.add_argument('--poll-seconds',type=int,default=30);a=ap.parse_args();pkg=Path(__file__).resolve().parent;req(sha(pkg/'authority'/'ALICE_MC10D_PUBLIC_JUDGE_QUALIFICATION_REBASE_v1.8.5.zip')==V185_SHA,'v185 parent hash');req(sha(pkg/'authority'/'ALICE_MC10D_GLM_Q04_DIAGNOSTIC_v1.0.0.zip')==DIAG_PKG_SHA,'diagnostic package hash');req(sha(pkg/'authority'/'mc10d_public_judge_qualification_worker_decision_v2.py')==DECISION_SHA,'decision worker hash');req(sha(pkg/'mc10d_public_judge_qualification_engine_v186.py')==ENGINE_SHA,'engine hash');freeze=Path(a.freeze_bundle);req(freeze.is_file() and sha(freeze)==FREEZE,'freeze')
 with tempfile.TemporaryDirectory(prefix='v186-outer-') as td0:
  td=Path(td0);safe_extract(pkg/'authority'/'ALICE_MC10D_PUBLIC_JUDGE_QUALIFICATION_REBASE_v1.8.5.zip',td/'v185');v185=one(td/'v185');# reuse v185's v182 utility parent to verify repo/amendments/infra
  safe_extract(v185/'authority'/'ALICE_MC10D_PUBLIC_JUDGE_QUALIFICATION_REBASE_v1.8.2.zip',td/'v182');v182=one(td/'v182');u=load(v182/'mc10d_public_judge_qualification_rebase_controller_v182.py','v182utility_v186');u.verify_repo(Path(a.repo_root));am=u.verify_amendment(v182,Path(a.vault_root));cl=u.verify_clarification(v182,Path(a.vault_root));sc=Path(a.vault_root)/DATASET_REL/'audits'/SC_INSTALL/'RATIFICATION_RECEIPT.json';req(sc.is_file() and sha(sc)==SC_RECEIPT,'decision scoring receipt');diag=validate_diag(Path(a.vault_root));prof=ratify_profile(pkg,Path(a.vault_root),diag);infra,rclone,cfg=u.verify_infra(Path(a.vault_root));u.reconcile_magnolia_history();vroot,_,_=u.exact_parent_and_amendments(v182,td/'parents');env=os.environ.copy();env['ALICE_MC10D_V172_ROOT']=str(vroot);env['ALICE_MC10D_DECISION_WORKER']=str(pkg/'authority'/'mc10d_public_judge_qualification_worker_decision_v2.py');env['ALICE_MC10D_BUDGET_RATIFICATION_RECEIPT']=str(am/'RATIFICATION_RECEIPT.json');env['ALICE_MC10D_CLARIFICATION_RATIFICATION_RECEIPT']=str(cl/'RATIFICATION_RECEIPT.json');env['ALICE_MC10D_SCORING_RATIFICATION_RECEIPT']=str(sc);env['ALICE_MC10D_GLM_PROFILE_RATIFICATION_RECEIPT']=str(prof/'RATIFICATION_RECEIPT.json');env['ALICE_MC10D_GLM_EFFECTIVE_POLICY']=str(prof/'mc10d_public_judge_qualification_policy_v1_glm_thinking_off.json');cmd=[sys.executable,str(pkg/'mc10d_public_judge_qualification_engine_v186.py'),'--repo-root',a.repo_root,'--vault-root',a.vault_root,'--freeze-bundle',str(freeze),'--output',a.output,'--timeout-hours',str(a.timeout_hours),'--poll-seconds',str(a.poll_seconds)];cp=subprocess.run(cmd,env=env);code=cp.returncode;print('v186_engine_exit='+str(code));
  if code in {75,76}:return code
  req(code==0,'v186 engine rc '+str(code));out=Path(a.output);req(out.is_file(),'v186 pointwise bundle missing');bind=validate_bundle(out,td/'bundlecheck');digest=sha(out);remote='rayan_gdrive:Rayan-Compute/checkpoints/'+digest+'/mc10d-pointwise-ready-v1.8.6.zip';cp2=subprocess.run([str(rclone),'copyto',str(out),remote,'--immutable','--config',str(cfg)],capture_output=True,text=True);req(cp2.returncode==0,'Drive upload');qroot=Path(a.vault_root)/DATASET_REL/'audits'/'alice-mc10d-repair-qualify-refreeze-v1-3.work'/'judge_qualification';qr={}
  for f in ['gemma','glm']:
   q=qroot/f;qr[f]={'result_sha256':sha(q/'mc10d_public_judge_qualification_result.json'),'rows_sha256':sha(q/'mc10d_public_judge_qualification_rows.jsonl'),'qualified_profile':rj(q/'mc10d_public_judge_qualification_result.json')['qualified_profile'],'reused_v182_rows':bool(rj(q/'qualification_request.json').get('reused_preserved_v182_rows',False))}
  receipt={'artifact_id':'alice.MC10D.public-judge-qualification-rebase.receipt.v1.8.6','canonical_main':MAIN,'decision_scoring_ratification_receipt_sha256':SC_RECEIPT,'glm_profile_ratification_receipt_sha256':PROFILE_RECEIPT_SHA,'effective_glm_policy_sha256':EFFECTIVE_POLICY_SHA,'qualification_results':qr,'pointwise_ready_bundle_sha256':digest,'pointwise_ready_drive_path':remote,'effective_pool':287,'deferred_slots':1,'pointwise_screen_started':False,'A_SYN_accepted':0,'A_SYN_promoted':0,'model_training':False,'stage_g_closed':False,'phase2_replaced':False,'next_action':'RATIFY_MC10D_CONTROLLED_SYNTHESIS_BREADTH_AMENDMENT_V1_0_4_THEN_POINTWISE_SCOPE_SCREEN_CURRENT_EFFECTIVE_POOL'};rp=Path(a.vault_root)/'tools'/'rayan-compute'/'mc10d'/'public-judge-qualification-rebase-v1.8.6-receipt.json';wj(rp,receipt);print('mc10d_v186_public_judge_qualification_rebase_complete=true');print('all_four_public_judges_bound=true');print('gemma_profile=thinking_on glm_profile=thinking_off');print('gemma_remote_rerun=false glm_fresh_full_family=true');print('pointwise_screen_started=false');print('pointwise_ready_bundle_sha256='+digest);return 0
if __name__=='__main__':
 try:raise SystemExit(main())
 except Stop as e:print('MC10D_V186_DETERMINISTIC_STOP: '+str(e),file=sys.stderr);raise SystemExit(76)
